# Generated by Django 2.2.3 on 2020-04-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20200415_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='appeared_at',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='disappeared_at',
        ),
    ]
