# Generated by Django 2.2.3 on 2020-04-14 22:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20200415_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 22, 11, 46, 309672, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 22, 11, 50, 246462, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
